FROM python:3.7-slim-buster
RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y build-essential libmariadb-dev-compat \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install mysqlclient==1.4.2.post1 \
    && apt-get remove -y build-essential \
    && apt-get autoremove -y \
    && apt-get clean
RUN pip3 install pika==1.0.1
COPY ./binancetradingbot /binancetradingbot
WORKDIR /binancetradingbot
CMD ["python3", "./fetcher_mainfile.py"]
